apiVersion: apps/v1
kind: Deployment
metadata:
  name: shanthinsdeploy1
  labels:
    app: shanthiinsdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shanthiinsdeploy
  template:
    metadata:
      labels:
        app: shanthiinsdeploy
    spec:
      containers:
      - name: shanthicontainer
        image: shanth19611356248/insurence_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shanthiservice
  labels:
    app: shanthiinsdeploy
spec:
  selector:
    app: shanthiinsdeploy

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
